// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: grpc_proto/telemetry.proto

package grpc_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Timestamp in nanoseconds, set by streamer
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	GpuId         string                 `protobuf:"bytes,3,opt,name=gpu_id,json=gpuId,proto3" json:"gpu_id,omitempty"`
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ModelName     []string               `protobuf:"bytes,6,rep,name=modelName,proto3" json:"modelName,omitempty"` // repeated for multiple modelName fields
	Namespace     string                 `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Value         float64                `protobuf:"fixed64,8,opt,name=value,proto3" json:"value,omitempty"`
	LabelsRaw     string                 `protobuf:"bytes,9,opt,name=labels_raw,json=labelsRaw,proto3" json:"labels_raw,omitempty"`
	MessageId     string                 `protobuf:"bytes,20,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // populated only on dispatch to collector; empty when streamer sends
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_grpc_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryRequest) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *TelemetryRequest) GetGpuId() string {
	if x != nil {
		return x.GpuId
	}
	return ""
}

func (x *TelemetryRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *TelemetryRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TelemetryRequest) GetModelName() []string {
	if x != nil {
		return x.ModelName
	}
	return nil
}

func (x *TelemetryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TelemetryRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelemetryRequest) GetLabelsRaw() string {
	if x != nil {
		return x.LabelsRaw
	}
	return ""
}

func (x *TelemetryRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_grpc_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TelemetryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// New ack RPC
type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_grpc_proto_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *AckRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_grpc_proto_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *AckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_grpc_proto_telemetry_proto protoreflect.FileDescriptor

const file_grpc_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1agrpc_proto/telemetry.proto\x12\ttelemetry\"\xa4\x02\n" +
	"\x10TelemetryRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12\x15\n" +
	"\x06gpu_id\x18\x03 \x01(\tR\x05gpuId\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12\x1c\n" +
	"\tmodelName\x18\x06 \x03(\tR\tmodelName\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\tR\tnamespace\x12\x14\n" +
	"\x05value\x18\b \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"labels_raw\x18\t \x01(\tR\tlabelsRaw\x12\x1d\n" +
	"\n" +
	"message_id\x18\x14 \x01(\tR\tmessageId\"G\n" +
	"\x11TelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\n" +
	"AckRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"A\n" +
	"\vAckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xed\x01\n" +
	"\x10TelemetryService\x12J\n" +
	"\rSendTelemetry\x12\x1b.telemetry.TelemetryRequest\x1a\x1c.telemetry.TelemetryResponse\x12N\n" +
	"\x10CollectTelemetry\x12\x1b.telemetry.TelemetryRequest\x1a\x1b.telemetry.TelemetryRequest0\x01\x12=\n" +
	"\fAckTelemetry\x12\x15.telemetry.AckRequest\x1a\x16.telemetry.AckResponseB\x19Z\x17./grpc_proto;grpc_protob\x06proto3"

var (
	file_grpc_proto_telemetry_proto_rawDescOnce sync.Once
	file_grpc_proto_telemetry_proto_rawDescData []byte
)

func file_grpc_proto_telemetry_proto_rawDescGZIP() []byte {
	file_grpc_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_grpc_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_telemetry_proto_rawDesc), len(file_grpc_proto_telemetry_proto_rawDesc)))
	})
	return file_grpc_proto_telemetry_proto_rawDescData
}

var file_grpc_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_proto_telemetry_proto_goTypes = []any{
	(*TelemetryRequest)(nil),  // 0: telemetry.TelemetryRequest
	(*TelemetryResponse)(nil), // 1: telemetry.TelemetryResponse
	(*AckRequest)(nil),        // 2: telemetry.AckRequest
	(*AckResponse)(nil),       // 3: telemetry.AckResponse
}
var file_grpc_proto_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.TelemetryService.SendTelemetry:input_type -> telemetry.TelemetryRequest
	0, // 1: telemetry.TelemetryService.CollectTelemetry:input_type -> telemetry.TelemetryRequest
	2, // 2: telemetry.TelemetryService.AckTelemetry:input_type -> telemetry.AckRequest
	1, // 3: telemetry.TelemetryService.SendTelemetry:output_type -> telemetry.TelemetryResponse
	0, // 4: telemetry.TelemetryService.CollectTelemetry:output_type -> telemetry.TelemetryRequest
	3, // 5: telemetry.TelemetryService.AckTelemetry:output_type -> telemetry.AckResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_telemetry_proto_init() }
func file_grpc_proto_telemetry_proto_init() {
	if File_grpc_proto_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_telemetry_proto_rawDesc), len(file_grpc_proto_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_grpc_proto_telemetry_proto_depIdxs,
		MessageInfos:      file_grpc_proto_telemetry_proto_msgTypes,
	}.Build()
	File_grpc_proto_telemetry_proto = out.File
	file_grpc_proto_telemetry_proto_goTypes = nil
	file_grpc_proto_telemetry_proto_depIdxs = nil
}
