// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/chowndarya/telemetry_pipeline/grpc_proto (interfaces: TelemetryServiceClient,TelemetryService_CollectTelemetryClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_telemetry_client.go -package=mocks github.com/chowndarya/telemetry_pipeline/grpc_proto TelemetryServiceClient,TelemetryService_CollectTelemetryClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	grpc_proto "github.com/chowndarya/telemetry_pipeline/grpc_proto"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockTelemetryServiceClient is a mock of TelemetryServiceClient interface.
type MockTelemetryServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryServiceClientMockRecorder
	isgomock struct{}
}

// MockTelemetryServiceClientMockRecorder is the mock recorder for MockTelemetryServiceClient.
type MockTelemetryServiceClientMockRecorder struct {
	mock *MockTelemetryServiceClient
}

// NewMockTelemetryServiceClient creates a new mock instance.
func NewMockTelemetryServiceClient(ctrl *gomock.Controller) *MockTelemetryServiceClient {
	mock := &MockTelemetryServiceClient{ctrl: ctrl}
	mock.recorder = &MockTelemetryServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryServiceClient) EXPECT() *MockTelemetryServiceClientMockRecorder {
	return m.recorder
}

// AckTelemetry mocks base method.
func (m *MockTelemetryServiceClient) AckTelemetry(ctx context.Context, in *grpc_proto.AckRequest, opts ...grpc.CallOption) (*grpc_proto.AckResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AckTelemetry", varargs...)
	ret0, _ := ret[0].(*grpc_proto.AckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AckTelemetry indicates an expected call of AckTelemetry.
func (mr *MockTelemetryServiceClientMockRecorder) AckTelemetry(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckTelemetry", reflect.TypeOf((*MockTelemetryServiceClient)(nil).AckTelemetry), varargs...)
}

// CollectTelemetry mocks base method.
func (m *MockTelemetryServiceClient) CollectTelemetry(ctx context.Context, in *grpc_proto.TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[grpc_proto.TelemetryRequest], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CollectTelemetry", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[grpc_proto.TelemetryRequest])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectTelemetry indicates an expected call of CollectTelemetry.
func (mr *MockTelemetryServiceClientMockRecorder) CollectTelemetry(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectTelemetry", reflect.TypeOf((*MockTelemetryServiceClient)(nil).CollectTelemetry), varargs...)
}

// SendTelemetry mocks base method.
func (m *MockTelemetryServiceClient) SendTelemetry(ctx context.Context, in *grpc_proto.TelemetryRequest, opts ...grpc.CallOption) (*grpc_proto.TelemetryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendTelemetry", varargs...)
	ret0, _ := ret[0].(*grpc_proto.TelemetryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTelemetry indicates an expected call of SendTelemetry.
func (mr *MockTelemetryServiceClientMockRecorder) SendTelemetry(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTelemetry", reflect.TypeOf((*MockTelemetryServiceClient)(nil).SendTelemetry), varargs...)
}

// MockTelemetryService_CollectTelemetryClient is a mock of TelemetryService_CollectTelemetryClient interface.
type MockTelemetryService_CollectTelemetryClient[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryService_CollectTelemetryClientMockRecorder[Res]
	isgomock struct{}
}

// MockTelemetryService_CollectTelemetryClientMockRecorder is the mock recorder for MockTelemetryService_CollectTelemetryClient.
type MockTelemetryService_CollectTelemetryClientMockRecorder[Res any] struct {
	mock *MockTelemetryService_CollectTelemetryClient[Res]
}

// NewMockTelemetryService_CollectTelemetryClient creates a new mock instance.
func NewMockTelemetryService_CollectTelemetryClient[Res any](ctrl *gomock.Controller) *MockTelemetryService_CollectTelemetryClient[Res] {
	mock := &MockTelemetryService_CollectTelemetryClient[Res]{ctrl: ctrl}
	mock.recorder = &MockTelemetryService_CollectTelemetryClientMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryService_CollectTelemetryClient[Res]) EXPECT() *MockTelemetryService_CollectTelemetryClientMockRecorder[Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockTelemetryService_CollectTelemetryClient[Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockTelemetryService_CollectTelemetryClientMockRecorder[Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockTelemetryService_CollectTelemetryClient[Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockTelemetryService_CollectTelemetryClient[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTelemetryService_CollectTelemetryClientMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTelemetryService_CollectTelemetryClient[Res])(nil).Context))
}

// Header mocks base method.
func (m *MockTelemetryService_CollectTelemetryClient[Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockTelemetryService_CollectTelemetryClientMockRecorder[Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockTelemetryService_CollectTelemetryClient[Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockTelemetryService_CollectTelemetryClient[Res]) Recv() (*grpc_proto.TelemetryRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*grpc_proto.TelemetryRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTelemetryService_CollectTelemetryClientMockRecorder[Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTelemetryService_CollectTelemetryClient[Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTelemetryService_CollectTelemetryClient[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTelemetryService_CollectTelemetryClientMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTelemetryService_CollectTelemetryClient[Res])(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockTelemetryService_CollectTelemetryClient[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTelemetryService_CollectTelemetryClientMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTelemetryService_CollectTelemetryClient[Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockTelemetryService_CollectTelemetryClient[Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockTelemetryService_CollectTelemetryClientMockRecorder[Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockTelemetryService_CollectTelemetryClient[Res])(nil).Trailer))
}
